// Display hints only. Never include these strings in defaults or saved drafts.
export const EJEMPLOS_ETAPA: Record<string,string> = {
 solicitante:'Ej.: María González', contacto:'Ej.: teléfono o correo de contacto', referencia:'Ej.: mensaje recibido por WhatsApp el 8 de octubre',
 proximoPaso:'Ej.: coordinar visita con el encargado y confirmar disponibilidad.',
 descripcion:'Ej.: verificar la fisura informada en la pared del estar.',
 esperaMotivo:'Ej.: se aguardó a que portería autorizara el ingreso.', autorizaAcceso:'Ej.: encargado del edificio', restricciones:'Ej.: acceso parcial; el dormitorio permaneció cerrado.',
 responsableVisita:'Ej.: nombre y especialidad del técnico', recibidoPor:'Ej.: nombre y función de quien recibió', propietario:'Ej.: nombre del propietario o solicitante',
 participantes:'Ej.: administrador del edificio, acompañante durante el recorrido.', edificio:'Ej.: Torre Güembé', unidad:'Ej.: Unidad 1041 · estar',
 recorrido:'Ej.: estar, pasillo y encuentro con el balcón.', sectoresNoVisitados:'Ej.: dormitorio cerrado; pendiente de coordinar acceso.',
 permiso:'Ej.: autorización de ingreso y permiso de trabajo en altura, si corresponde.', riesgos:'Ej.: piso húmedo en acceso al balcón.', medidasSeguridad:'Ej.: delimitar el sector y verificar protección antes de la actividad.',
 actividad:'Ej.: inspección visual y medición del ancho de la fisura.', metodo:'Ej.: medición con fisurómetro; fotos 1 y 2 del encuentro.',
 observacionesTecnicas:'Ej.: fisura visible en el encuentro; se registró ancho y extensión.', limitesVerificacion:'Ej.: no se inspeccionó el interior del muro.',
 compromisos:'Ej.: técnico enviará diagnóstico; administración confirmará el acceso.', representantesPrevistos:'Ej.: propietario y técnico interviniente',
 visitaReferencia:'Ej.: código de la ficha de visita y versión consultada', tecnico:'Ej.: nombre y especialidad', antecedentes:'Ej.: el cliente informó una fisura visible desde la semana anterior.',
 condiciones:'Ej.: inspección visual con acceso parcial al sector.', hallazgos:'Ej.: fisura localizada y evidencia registrada en fotos 1 y 2.', pruebas:'Ej.: mediciones efectuadas, instrumento y resultado.', causa:'Ej.: hipótesis técnica y evidencia; indicar si requiere una prueba adicional.',
 planoReferencia:'Ej.: estar, muro lindero al pasillo, eje B–3.', alcance:'Ej.: reparar el sector identificado y restituir su terminación.', exclusiones:'Ej.: pintura de ambientes no afectados; sujeto a revisión del soporte.',
 criterios:'Ej.: superficie uniforme, sin desprendimientos y con terminación acordada.', cronograma:'Ej.: prever secado entre reparación y pintura; referencia del acuerdo.', condicionesOperativas:'Ej.: acceso de 08:00 a 12:00 y protección del mobiliario.', fundamentoGarantia:'Ej.: cláusula contractual y evidencia que sustenta la evaluación.',
 trabajo:'Ej.: reparar fisura en muro del estar', rubro:'Ej.: albañilería', profesional:'Ej.: oficial albañil / pintor', criterio:'Ej.: terminación continua, verificada con el criterio acordado.',
 alcanceReferencia:'Ej.: código y versión del plan aprobado; referencia de la autorización.', acumulado:'Ej.: reparación terminada; pendiente de pintura y verificación.', porcentaje:'Ej.: 60', metodoPorcentaje:'Ej.: actividades terminadas sobre el total del plan.',
 desvios:'Ej.: secado adicional; impacto previsto de un día.', proximoPeriodo:'Ej.: aplicar terminación y verificar con el responsable.', previsto:'Ej.: reparar y preparar el soporte', realizado:'Ej.: reparación completada; soporte en secado', saldo:'Ej.: pintura y verificación final',
 cambiosAprobados:'Ej.: referencia de la autorización de un trabajo adicional', ejecucionPorItem:'Ej.: se reparó el sector y se restituyó la terminación acordada.',
 verificacion:'Ej.: control visual y de adherencia; resultado, técnico y fecha.', limpiezaVerificada:'Ej.: sector limpio; verificado por el responsable en la fecha indicada.', danosVerificados:'Ej.: inspección de áreas contiguas y resultado observado.',
 pendientes:'Ej.: revisión de terminación coordinada para la próxima visita.', entregables:'Ej.: informe técnico, fotos finales y recomendaciones de mantenimiento.', conclusion:'Ej.: resultado comprobado respecto del plan y restricciones pendientes.', autorizacionInterna:'Ej.: responsable y referencia de su autorización', resultado:'Ej.: cumple el criterio acordado', verificadorFecha:'Ej.: nombre del técnico y fecha del control',
 receptor:'Ej.: nombre completo de quien recibe', documentoReceptor:'Ej.: documento de identidad o RUC', organizacion:'Ej.: consorcio o empresa representada', cargo:'Ej.: propietario / administrador', facultad:'Ej.: autorización o representación acreditada',
 cierreReferencia:'Ej.: código del informe de cierre y revisión entregada', objetoEntrega:'Ej.: reparación y terminación del muro identificado en la OT.', observacionesCliente:'Ej.: observación expresada por el cliente al recibir el trabajo.', reservas:'Ej.: aspecto pendiente y tratamiento acordado; completar según corresponda.',
 anexosEntregados:'Ej.: informe de cierre y registro fotográfico final.', garantiaReferencia:'Ej.: cláusula y documento contractual aplicable', garantiaCondiciones:'Ej.: cobertura y condiciones pactadas; no agregar compromisos no acordados.',
 respondente:'Ej.: nombre de la persona que responde', relacionConOT:'Ej.: propietario de la unidad atendida', referenciaFuente:'Ej.: formulario o comunicación donde consta la respuesta', sugerencias:'Ej.: ¿qué podríamos mejorar en una próxima atención?',
 observaciones:'Ej.: detalle adicional pertinente a esta etapa.',
};
