import {useCallback,useContext,useEffect,useId,useState} from 'react';
import {supabase} from '../../db/supabase';
import {assertSession,sessionTicket} from '../../security/sessionScope';
import {useAccessStore,type ContextoAcceso} from '../../stores/accessStore';
import {useProyectosStore} from '../../stores/proyectosStore';
import {clavesRequeridasFicha,datosEditables,datosNuevos,faltantesFicha,gruposMaestros,guardarMaestro,listarMaestros,nombresMaestros,normalizarMaestro,vincularContacto,type CampoMaestro,type DatosMaestros,type FichaMaestra,type TipoMaestro} from '../../services/masterDirectoryService';
import {guardarFotoDirectorio} from '../../services/directoryPhotoService';
import {FotoDirectorio} from '../plano/FotoDirectorio';
import {VoiceInputButton} from '../ui/VoiceInputButton';
import {EtiquetaObra,SelectorColorObra} from '../ui/ColorObra';
import {PanelAdministracion} from './PanelAdministracion';
import {EliminarDirectorio} from './EliminarDirectorio';
import {GuardiaAdministracionContext} from './guardiaAdministracionContext';
import {UbicacionesAdministracion} from './UbicacionesAdministracion';
import styles from './AdministracionCreador.module.css';
import s from './FichasAdministracion.module.css';

const str=(d:DatosMaestros,k:string)=>String(d[k]??'');
const labelOpcion=(v:string)=>({persona:'Persona',empresa:'Empresa',independiente:'Independiente'}[v]??v);
export function CampoFicha({campo,datos,cambiar,disabled=false,required=false}:{campo:CampoMaestro;datos:DatosMaestros;cambiar:(key:string,value:string)=>void;disabled?:boolean;required?:boolean}){
 const value=str(datos,campo.key),max=campo.max??(campo.key.includes('correo')?254:campo.key.includes('telefono')||campo.key==='identificacion'?80:campo.key.includes('direccion')||campo.key==='mapa'||campo.key==='web'?500:160);
 return <label className={`${s.field} ${campo.full?s.full:''}`}><span className={s.label}>{campo.label}{required?' *':''}{!campo.opciones&&<VoiceInputButton compact disabled={disabled} value={value} maxLength={max} onChange={v=>cambiar(campo.key,v)}/>}</span>{campo.opciones?<select disabled={disabled} value={value} onChange={e=>cambiar(campo.key,e.target.value)}><option value="">Seleccionar…</option>{!campo.opciones.includes(value)&&value&&<option value={value}>{value} (registro anterior)</option>}{campo.opciones.map(v=><option key={v} value={v}>{labelOpcion(v)}</option>)}</select>:campo.area?<textarea rows={4} disabled={disabled} aria-label={campo.label} maxLength={max} value={value} placeholder={campo.ejemplo} onChange={e=>cambiar(campo.key,e.target.value)}/>:<input disabled={disabled} aria-label={campo.label} type={campo.key.includes('correo')?'email':campo.key.includes('telefono')?'tel':'text'} maxLength={max} value={value} placeholder={campo.ejemplo} onChange={e=>cambiar(campo.key,e.target.value)}/>}</label>;
}

export function BuscarFicha({registros,value,onChange,label,disabled=false,onNuevo,nuevoDisabled=false}:{registros:FichaMaestra[];value:string;onChange:(id:string)=>void;label:string;disabled?:boolean;onNuevo?:()=>void;nuevoDisabled?:boolean}){
 const [texto,setTexto]=useState('');
 const actual=registros.find(r=>r.id===value),resultados=registros.filter(r=>r.datos.activo!==false&&normalizarMaestro(Object.values(r.datos).join(' ')).includes(normalizarMaestro(texto)));
 return <div className={s.picker}><span>{label}</span>{actual?<div className={s.selected}><div><strong>{str(actual.datos,'nombre')}{actual.datos.activo===false?' · Inactivo':''}</strong><small>{[actual.datos.telefono,actual.datos.correo].filter(Boolean).join(' · ')}</small></div><button type="button" className={styles.secondaryButton} disabled={disabled} onClick={()=>onChange('')}>Cambiar</button></div>:<><input type="search" aria-label={label} placeholder="Buscar por nombre, teléfono o correo…" disabled={disabled} value={texto} onChange={e=>setTexto(e.target.value)}/>{!disabled&&<div className={s.options}>{resultados.slice(0,30).map(r=><button type="button" key={r.id} onClick={()=>{onChange(r.id);setTexto('')}}>{str(r.datos,'nombre')}<small> · {str(r.datos,'telefono')||str(r.datos,'correo')}</small></button>)}{!resultados.length&&<small>No hay coincidencias.</small>}{resultados.length>30&&<small>Escribí más para acotar la búsqueda.</small>}</div>}</>}{onNuevo&&!disabled&&<button className={styles.secondaryButton} type="button" disabled={nuevoDisabled} onClick={onNuevo}>+ Nuevo contacto</button>}</div>;
}

function datosFicha(tipo:TipoMaestro,ficha?:FichaMaestra):DatosMaestros{
 const d=ficha?datosEditables(ficha.datos):datosNuevos(tipo);
 if(tipo==='obra'&&!d.color)d.color='#3B82F6';
 if(ficha&&tipo!=='contacto'){
  const principal=ficha.vinculos.find(v=>v.principal&&v.activo)??ficha.vinculos.find(v=>v.activo);
  if(principal&&!d.contacto_principal_id){d.contacto_principal_id=principal.contacto_id;d.funcion_contacto=principal.funcion}
 }
 if(ficha&&tipo==='contacto'&&!d.vinculo_id){const link=ficha.vinculos.find(v=>v.activo);if(link){for(const tipoLink of ['empresa','obra','cliente','contratista','ubicacion']){const id=link[`${tipoLink}_id` as keyof typeof link];if(typeof id==='string'){d.vinculo_tipo=tipoLink;d.vinculo_id=id;d.funcion=link.funcion;break}}}}
 return d;
}

async function actualizarContexto(){const ticket=sessionTicket();const r=await supabase.rpc('plan_contexto_acceso');assertSession(ticket);if(r.error)throw new Error(r.error.message);useAccessStore.setState({contexto:r.data as ContextoAcceso});await useProyectosStore.getState().cargarProyectos()}

export function FichasAdministracion({tipo,tenantId,onSeleccionar}:{tipo:TipoMaestro;tenantId:string;onSeleccionar:(id:string)=>void}){
 const guardia=useContext(GuardiaAdministracionContext);
 const [registros,setRegistros]=useState<FichaMaestra[]>([]),[buscar,setBuscar]=useState(''),[estado,setEstado]=useState('todos'),[version,setVersion]=useState(0),[cargando,setCargando]=useState(true),[empresaActiva,setEmpresaActiva]=useState(true),[error,setError]=useState('');
 const [editor,setEditor]=useState<{ficha?:FichaMaestra;lectura:boolean}|null>(null);
 useEffect(()=>{let active=true;void Promise.resolve().then(()=>Promise.all([listarMaestros(tipo,tenantId),tipo==='empresa'?Promise.resolve<FichaMaestra[]>([]):listarMaestros('empresa',tenantId)])).then(([r,empresas])=>{if(active){setEmpresaActiva((tipo==='empresa'?r:empresas).find(e=>e.id===tenantId)?.datos.activo!==false);setRegistros(r);setError('');setCargando(false)}}).catch(e=>{if(active){setError(e.message);setCargando(false)}});return()=>{active=false}},[tipo,tenantId,version]);
 const meta=nombresMaestros[tipo];
 const resultados=registros.filter(r=>(estado==='todos'||(estado==='activos'?r.datos.activo!==false:r.datos.activo===false))&&normalizarMaestro(Object.values(r.datos).join(' ')).includes(normalizarMaestro(buscar)));
 const abrir=(ficha?:FichaMaestra,lectura=false)=>guardia.solicitar(()=>setEditor({ficha,lectura}));
 return <section className={styles.workspace} aria-label={meta.plural}>
  <div className={styles.sectionHeader}><div><h2>{meta.plural}</h2><p>{registros.length} registrada(s) · Datos compartidos e historial conservado</p></div><button type="button" className={styles.primaryButton} disabled={cargando||(tipo!=='empresa'&&!empresaActiva)} title={!empresaActiva?'Reactivá la empresa para crear fichas':undefined} onClick={()=>abrir()}>+ Crear {meta.singular}</button></div>
  {tipo==='empresa'&&!tenantId&&<p className={styles.hint}>Seleccioná una empresa para administrar sus obras, clientes, contratistas y contactos.</p>}
  <div className={s.toolbar}><label className={styles.search}>Buscar {meta.singular}<input type="search" value={buscar} onChange={e=>setBuscar(e.target.value)} placeholder="Nombre, razón social, documento, teléfono, dirección…"/></label><label className={styles.field}>Estado<select className="app-select" value={estado} onChange={e=>setEstado(e.target.value)}><option value="todos">Todos</option><option value="activos">Activos</option><option value="inactivos">Inactivos</option></select></label></div>
  <div className={styles.recordList}>{resultados.map(r=><article key={r.id} className={styles.recordRow} style={{borderLeft:`3px solid ${tipo==='obra'?str(r.datos,'color')||meta.color:meta.color}`}}><div className={styles.recordPhoto}><FotoDirectorio tipo={tipo} id={r.id} nombre={str(r.datos,'nombre')}/></div><div className={styles.recordIdentity}>{tipo==='obra'?<EtiquetaObra nombre={str(r.datos,'nombre')} color={str(r.datos,'color')}/>:<strong>{str(r.datos,'nombre')}</strong>}<small>{[r.datos.identificacion,r.datos.ciudad,r.datos.telefono].filter(Boolean).join(' · ')||str(r.datos,'direccion')||meta.plural}</small><small>{r.datos.activo===false?'Inactiva':'Activa'} · {r.completa?'Completa':'Pendiente de completar'}{tipo==='empresa'&&r.id===tenantId?' · Seleccionada':''}</small></div><div className={styles.creationActions}><button type="button" className={styles.secondaryButton} disabled={tipo==='empresa'&&r.id!==tenantId} title={tipo==='empresa'&&r.id!==tenantId?'Seleccioná esta empresa para ver su ficha':undefined} aria-label={`Ver ${meta.singular} ${r.datos.nombre}`} onClick={()=>abrir(r,true)}>Ver</button>{tipo==='empresa'&&<button type="button" className={styles.secondaryButton} disabled={r.id===tenantId} onClick={()=>guardia.solicitar(()=>{setEditor(null);onSeleccionar(r.id)})}>Seleccionar</button>}<button type="button" className={styles.secondaryButton} disabled={tipo==='empresa'&&r.id!==tenantId} title={tipo==='empresa'&&r.id!==tenantId?'Seleccioná esta empresa antes de editarla':undefined} aria-label={`Editar ${meta.singular} ${r.datos.nombre}`} onClick={()=>abrir(r)}>Editar</button><EliminarDirectorio tipo={tipo} id={r.id} nombre={str(r.datos,'nombre')} onEliminar={()=>{setEditor(null);setVersion(v=>v+1);if(tipo==='empresa'&&r.id===tenantId)onSeleccionar('');void actualizarContexto().catch(e=>setError(e.message))}}/></div></article>)}</div>
  {cargando&&<p role="status">Cargando fichas…</p>}{!cargando&&!resultados.length&&<p className={styles.hint}>{buscar?'No hay coincidencias.':'Todavía no hay fichas en esta selección.'}</p>}{error&&<p role="alert">{error}</p>}
  {editor&&<EditorFicha key={`${tipo}-${editor.ficha?.id??'nueva'}-${editor.lectura}`} tipo={tipo} tenantId={tenantId} ficha={editor.ficha} lectura={editor.lectura} permiteAltas={empresaActiva} onCerrar={()=>setEditor(null)} onGuardado={id=>{setVersion(v=>v+1);if(tipo==='empresa'&&!editor.ficha)onSeleccionar(id)}}/>}
 </section>;
}

function EditorFicha({tipo,tenantId,ficha,lectura=false,onCerrar,onGuardado,inicial,onContactoNuevo,permiteAltas=true}:{tipo:TipoMaestro;tenantId:string;ficha?:FichaMaestra;lectura?:boolean;onCerrar:()=>void;onGuardado:(id:string)=>void;inicial?:DatosMaestros;onContactoNuevo?:(id:string)=>void;permiteAltas?:boolean}){
 const guardia=useContext(GuardiaAdministracionContext),guardId=useId();
 const [datos,setDatos]=useState<DatosMaestros>(()=>({...datosFicha(tipo,ficha),...inicial})),[base,setBase]=useState(()=>JSON.stringify({...datosFicha(tipo,ficha),...inicial})),[id,setId]=useState(ficha?.id??''),[foto,setFoto]=useState<File|null>(null),[busy,setBusy]=useState(false),[mensaje,setMensaje]=useState(''),[error,setError]=useState('');
 const [contactos,setContactos]=useState<FichaMaestra[]>([]),[entidades,setEntidades]=useState<Record<string,FichaMaestra[]>>({}),[crearContacto,setCrearContacto]=useState(false),[destinoContacto,setDestinoContacto]=useState<{seleccionar:(id:string)=>void;ubicacion:string}|null>(null),[vinculos,setVinculos]=useState(ficha?.vinculos??[]);
 const [busquedaTipo,setBusquedaTipo]=useState(str(datos,'vinculo_tipo')||'obra');
 const scope=tipo==='empresa'?(id||''):tenantId;
 const dirty=!lectura&&(JSON.stringify(datos)!==base||!!foto);
 useEffect(()=>guardia.registrar(guardId,dirty,busy),[guardia,guardId,dirty,busy]);
 const cargarContactos=useCallback(async()=>{if(!scope){setContactos([]);return}const r=await listarMaestros('contacto',scope);setContactos(r)},[scope]);
 useEffect(()=>{let active=true;if(!scope)return;void listarMaestros('contacto',scope).then(r=>{if(active)setContactos(r)}).catch(e=>{if(active)setError(e.message)});if(tipo==='contacto')void Promise.all((['empresa','obra','cliente','contratista'] as const).map(async kind=>[kind,await listarMaestros(kind,scope)] as const)).then(r=>{if(active)setEntidades(prev=>({...prev,...Object.fromEntries(r.map(([k,v])=>[k,v.filter(f=>f.tenant_id===scope)]))}))}).catch(e=>{if(active)setError(e.message)});if(tipo==='contacto'){const ticket=sessionTicket();void Promise.resolve(supabase.from('plan_cliente_ubicaciones').select('id,tenant_id,nombre_obra,direccion,unidad,activo').eq('tenant_id',scope).order('nombre_obra')).then(r=>{assertSession(ticket);if(r.error)throw new Error(r.error.message);if(active)setEntidades(prev=>({...prev,ubicacion:(r.data??[]).map(u=>({id:u.id,tenant_id:u.tenant_id,datos:{nombre:`${u.nombre_obra}${u.unidad?' · '+u.unidad:''}`,direccion:u.direccion,activo:u.activo},vinculos:[],completa:true,codigo:null,actualizado_en:null}))}))}).catch(e=>{if(active)setError(e.message)})}return()=>{active=false}},[scope,tipo]);
 const cambiar=(key:string,value:string|boolean|null)=>setDatos(d=>({...d,[key]:value}));
 const missing=faltantesFicha(tipo,datos),meta=nombresMaestros[tipo];
 async function guardar(completa:boolean){if(busy||lectura)return;setBusy(true);setError('');setMensaje('');try{const saved=await guardarMaestro(tipo,tipo==='empresa'?id:tenantId,id,datos,completa);setId(saved);setBase(JSON.stringify(datos));onGuardado(saved);if(foto){try{await guardarFotoDirectorio(tipo,saved,foto);setFoto(null)}catch(e){throw new Error('La ficha se guardó. Falta guardar la foto: '+(e instanceof Error?e.message:'Reintentá.'),{cause:e})}}const refreshed=(await listarMaestros(tipo,tipo==='empresa'?saved:tenantId)).find(f=>f.id===saved);if(refreshed)setVinculos(refreshed.vinculos);setMensaje(completa?'Ficha completa guardada.':'Ficha guardada pendiente de completar.');if(tipo==='empresa'||tipo==='obra')await actualizarContexto();if(onContactoNuevo)onContactoNuevo(saved)}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.')}finally{setBusy(false)}}
 async function cambiarVinculo(link:typeof vinculos[number]){if(busy||lectura)return;setBusy(true);setError('');try{const kind=(['empresa','obra','cliente','contratista','ubicacion'] as const).find(k=>link[`${k}_id`]);if(!kind)return;await vincularContacto(scope,link.contacto_id,kind,String(link[`${kind}_id`]),link.funcion,!link.activo,link.principal);const fresh=(await listarMaestros(tipo,scope)).find(r=>r.id===id);if(fresh)setVinculos(fresh.vinculos);setMensaje('Vínculo actualizado. La persona y el historial se conservan.')}catch(e){setError(e instanceof Error?e.message:'No se pudo actualizar.')}finally{setBusy(false)}}
 return <><PanelAdministracion cancelarCompacto={!lectura} titulo={`${lectura?'Ficha de':id?'Editar':'Crear'} ${meta.singular}`} busy={busy} onCerrar={()=>guardia.solicitar(onCerrar,guardId)} acciones={!lectura&&<><button type="button" className={styles.secondaryButton} disabled={busy||!str(datos,'nombre').trim()} onClick={()=>void guardar(false)}>Guardar pendiente</button><button type="button" className={styles.primaryButton} disabled={busy||!!missing.length} title={missing.length?`Falta: ${missing.join(', ')}`:undefined} onClick={()=>void guardar(true)}>Guardar completa</button></>}>
  <div className={s.identity}><FotoDirectorio tipo={tipo} id={id||undefined} nombre={str(datos,'nombre')||`${tipo==='empresa'||tipo==='obra'?'Nueva':'Nuevo'} ${meta.singular}`} archivo={foto} onArchivo={lectura?undefined:setFoto} disabled={busy}/><div><strong>{str(datos,'nombre')||`${tipo==='empresa'||tipo==='obra'?'Nueva':'Nuevo'} ${meta.singular}`}</strong><label className={s.state}>Estado<select disabled={lectura||busy} aria-label="Estado de la ficha" value={datos.activo===false?'inactivo':'activo'} onChange={e=>cambiar('activo',e.target.value==='activo')}><option value="activo">Activa</option><option value="inactivo">Inactiva</option></select></label><small>{ficha?.codigo?`Código ${ficha.codigo} · `:''}{missing.length?'Pendiente de completar':'Datos principales completos'}</small></div></div>
  <p className={s.hint}>Inactiva: conserva su historial y evita nuevos vínculos. Pendiente: permite completar los datos después.</p>
  <fieldset className={styles.editorFields} disabled={busy||lectura}><div className={s.form}>{gruposMaestros[tipo].map(grupo=><details className={s.group} key={grupo.nombre} open={!grupo.extra}><summary>{grupo.nombre}</summary><div className={s.fields}>{grupo.campos.filter(c=>c.key!=='razon_social'||tipo==='empresa'||datos.tipo==='empresa'||!!datos.razon_social).map(c=><CampoFicha key={c.key} campo={c} required={clavesRequeridasFicha(tipo,datos).includes(c.key)} datos={datos} cambiar={cambiar} disabled={busy||lectura}/>)}</div></details>)}
   {tipo==='cliente'&&<fieldset className={s.classification}><legend>Clasificación interna del cliente</legend><strong>Potencialmente conflictivo *</strong><div>{[true,false].map(v=><label key={String(v)}><input type="radio" name={`conflictivo-${guardId}`} checked={datos.potencialmente_conflictivo===v} onChange={()=>cambiar('potencialmente_conflictivo',v)} disabled={busy||lectura}/>{v?'Sí':'No'}</label>)}</div><small>Elegí una opción para completar la ficha. No aparece en los informes del cliente.</small></fieldset>}
   {tipo==='obra'&&<details className={s.group}><summary>Color de referencia · 60 colores</summary><SelectorColorObra value={str(datos,'color')||'#3B82F6'} nombre={str(datos,'nombre')} disabled={busy||lectura} onChange={v=>cambiar('color',v)}/></details>}
   {tipo!=='contacto'&&<details className={s.group} open={tipo==='obra'||tipo==='empresa'||tipo==='contratista'}><summary>Contacto principal y función</summary>{tipo==='empresa'&&!id?<p className={s.hint}>Guardá primero la empresa como pendiente. Después podrás crear o vincular su contacto.</p>:<><BuscarFicha registros={contactos} value={str(datos,'contacto_principal_id')} onChange={v=>cambiar('contacto_principal_id',v)} label="Contacto principal" disabled={busy||lectura} nuevoDisabled={!permiteAltas} onNuevo={()=>{setDestinoContacto(null);setCrearContacto(true)}}/><CampoFicha campo={{key:'funcion_contacto',label:'Función en esta ficha',ejemplo:'Ej.: Administradora / representante',full:true}} datos={datos} cambiar={cambiar} disabled={busy||lectura}/></>}</details>}
   {tipo==='contacto'&&<details className={s.group} open><summary>Entidad y función · una persona puede tener varios vínculos</summary><label className={s.field}>Vincular a<select disabled={busy||lectura} value={busquedaTipo} onChange={e=>{setBusquedaTipo(e.target.value);setDatos(d=>({...d,vinculo_tipo:e.target.value,vinculo_id:'',funcion:''}))}}>{['empresa','obra','cliente','contratista','ubicacion'].map(k=><option key={k} value={k}>{k==='ubicacion'?'Ubicación':nombresMaestros[k as TipoMaestro].singular}</option>)}</select></label><BuscarFicha registros={entidades[busquedaTipo]??[]} value={str(datos,'vinculo_id')} onChange={v=>setDatos(d=>({...d,vinculo_tipo:busquedaTipo,vinculo_id:v,funcion:vinculos.find(link=>link[`${busquedaTipo}_id` as keyof typeof link]===v)?.funcion??''}))} label="Registro vinculado" disabled={busy||lectura}/><CampoFicha campo={{key:'funcion',label:'Función en el vínculo',ejemplo:'Ej.: Administradora de la obra'}} datos={datos} cambiar={cambiar} disabled={busy||lectura}/></details>}
  </div></fieldset>
  {id&&vinculos.length>0&&<details className={s.group}><summary>{tipo==='contacto'?'Vínculos registrados':'Todos los contactos'} · {vinculos.length}</summary>{vinculos.map(v=><div className={s.link} key={v.id}><strong>{tipo==='contacto'?(Object.values(entidades).flat().find(r=>r.id===(v.empresa_id||v.obra_id||v.cliente_id||v.contratista_id))?.datos.nombre??'Ubicación vinculada'):v.contacto_nombre}</strong><span>{v.funcion}{v.principal?' · Principal':''} · {v.activo&&v.contacto_activo?'Activo':'Inactivo'}</span><small>{[v.telefono,v.correo].filter(Boolean).join(' · ')}</small>{!lectura&&tipo==='contacto'&&<button type="button" className={styles.secondaryButton} disabled={busy} onClick={()=>{const kind=(['empresa','obra','cliente','contratista','ubicacion'] as const).find(k=>v[`${k}_id`]);if(kind){setBusquedaTipo(kind);setDatos(d=>({...d,vinculo_tipo:kind,vinculo_id:String(v[`${kind}_id`]),funcion:v.funcion}))}}}>Editar función</button>}{!lectura&&<button type="button" className={styles.secondaryButton} disabled={busy||dirty||(!v.activo&&!v.contacto_activo)} title={dirty?'Guardá primero los cambios de la ficha':undefined} onClick={()=>void cambiarVinculo(v)}>{v.activo?'Desactivar vínculo':'Reactivar vínculo'}</button>}</div>)}</details>}
  {tipo==='cliente'&&id&&<UbicacionesAdministracion tenantId={tenantId} clienteId={id} contactos={contactos} lectura={lectura} permiteAltas={permiteAltas&&datos.activo!==false} onNuevoContacto={(seleccionar,ubicacion)=>{setDestinoContacto({seleccionar,ubicacion});setCrearContacto(true)}}/>}
  {missing.length>0&&!lectura&&<p className={s.hint}>Para completar: {missing.join(' · ')}.</p>}{id&&ficha?.actualizado_en&&<p className={s.hint}>Última actualización: {new Date(ficha.actualizado_en).toLocaleString('es-PY')}.</p>}{error&&<p role="alert" className={s.error}>{error}</p>}{mensaje&&<p role="status">{mensaje}</p>}
 </PanelAdministracion>
 {crearContacto&&<EditorFicha tipo="contacto" tenantId={scope} inicial={{vinculo_tipo:destinoContacto?'ubicacion':tipo,vinculo_id:destinoContacto?destinoContacto.ubicacion:id,funcion:destinoContacto?'Contacto de ubicación':str(datos,'funcion_contacto')}} onCerrar={()=>setCrearContacto(false)} onGuardado={()=>{}} onContactoNuevo={nuevo=>{if(destinoContacto)destinoContacto.seleccionar(nuevo);else cambiar('contacto_principal_id',nuevo);void cargarContactos();setCrearContacto(false)}}/>}
 </>;
}
