import {useCallback,useContext,useEffect,useId,useRef,useState,type ReactNode} from 'react';
import {useAccessStore} from '../../stores/accessStore';
import {permissionCatalog} from '../../security/permissionCatalog';
import {changedPermissions,effectivePermission,permissionLock,togglePermission} from '../../security/teamPermissionMatrix';
import {loadTeamPerson,searchTeamPeople,saveTeamPermissions,type TeamPerson,type TeamSnapshot} from '../../services/teamService';
import {coincideBusqueda} from '../../utils/busqueda';
import {SelectorBusqueda} from '../ui/SelectorBusqueda';
import {GuardiaAdministracionContext} from './guardiaAdministracionContext';
import {AvatarEquipo} from './AvatarEquipo';
import TooltipAyuda from '../ayuda/TooltipAyuda';
import s from './MatrizPermisos.module.css';
const profiles={jefe:'Jefe',tecnico:'Técnico',ayudante:'Ayudante',lector:'Lector'};
const defaults=['Órdenes de trabajo','Fotos y evidencias','Informes'];
const groups=[...defaults,...new Set(permissionCatalog.map(p=>p.group).filter(group=>!defaults.includes(group)))];
export function MatrizPermisos({tenantId,selectedPersonId}:{tenantId:string;selectedPersonId?:string}){
 const guard=useContext(GuardiaAdministracionContext),guardId=useId();
 const context=useAccessStore(v=>v.contexto),company=context?.empresas.find(e=>e.id===tenantId);
 const [snapshot,setSnapshot]=useState<TeamSnapshot|null>(null),[people,setPeople]=useState<TeamPerson[]>([]),[loading,setLoading]=useState(!!selectedPersonId),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [search,setSearch]=useState(''),[expanded,setExpanded]=useState(defaults),[selected,setSelected]=useState(selectedPersonId??'');
 const lock=useRef(false),mounted=useRef(true),changes=changedPermissions(snapshot?.usuarios??[],people),dirty=changes.length>0;
 useEffect(()=>guard.registrar(guardId,dirty,busy),[guard,guardId,dirty,busy]);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 useEffect(()=>{if(!selected)return;let active=true;void loadTeamPerson(tenantId,selected).then(result=>{if(active){setSnapshot(result);setPeople(structuredClone(result.usuarios));setLoading(false);}}).catch(e=>{if(active){setError(e.message);setLoading(false);}});return()=>{active=false;};},[tenantId,selected]);
 const lookup=useCallback(async(text:string)=>(await searchTeamPeople(tenantId,text)).map(p=>({id:p.id,nombre:p.nombre,detalle:`${profiles[p.perfil]} · ${p.email}${!p.activo?' · Desactivado':''}`})),[tenantId]);
 const canManage=!!context?.creador||!!company?.permisos?.includes('equipo.permisos'),person=people.find(p=>p.id===selected);
 const choose=(id:string)=>{if(id===selected)return;guard.solicitar(()=>{setSelected(id);setSnapshot(null);setPeople([]);setLoading(true);setError('');setMessage('');},guardId);};
 async function reload(){if(lock.current||!selected)return;setLoading(true);setError('');try{const fresh=await loadTeamPerson(tenantId,selected);if(mounted.current){setSnapshot(fresh);setPeople(structuredClone(fresh.usuarios));setMessage('Permisos actualizados.');}}catch(e){if(mounted.current)setError(e instanceof Error?e.message:'No se pudo actualizar.');}finally{if(mounted.current)setLoading(false);}}
 async function save(){if(lock.current||!changes.length)return;lock.current=true;setBusy(true);setError('');setMessage('');try{const fresh=await saveTeamPermissions(tenantId,changes);if(mounted.current){setSnapshot(fresh);setPeople(structuredClone(fresh.usuarios));setMessage('Permisos guardados. Se aplican también los límites de cada superior.');}}catch(e){if(mounted.current)setError(e instanceof Error?e.message:'No se pudo guardar.');}finally{lock.current=false;if(mounted.current)setBusy(false);}}
 const matches=(value:{group:string;label:string;key:string})=>coincideBusqueda(`${value.group} ${value.label} ${value.key}`,search);
 return <section className={s.workspace} aria-label="Matriz de permisos del equipo" aria-busy={loading||busy}>
  <header className={s.header}><div><h2>Permisos del usuario</h2><p>{company?.nombre}</p></div><button disabled={busy||loading||!selected} onClick={()=>guard.solicitar(()=>void reload(),guardId)}>Actualizar</button></header>
  <div className={s.userPicker}><span>Usuario</span><SelectorBusqueda label="Buscar usuario" value={person?{id:person.id,nombre:person.nombre}:undefined} buscar={lookup} onSeleccionar={choose} placeholder="Buscar por nombre o correo…" disabled={busy}/></div>
  {person&&<div className={s.identity}><AvatarEquipo person={person}/><div><strong>{person.nombre}</strong><small>{profiles[person.perfil]} · {person.activo?'Activo':'Desactivado'}{person.superior_id?` · depende de ${people.find(p=>p.id===person.superior_id)?.nombre??'su superior'}`:' · máxima autoridad de la empresa'}</small></div><span>Cupos autorizados: <strong>{person.cupos_tecnicos} técnicos · {person.cupos_ayudantes} ayudantes</strong><small>{person.obras.length} obra(s) · {person.editable?'Administrable':'Solo consulta'}</small></span></div>}
  {error&&<p className={s.error} role="alert">{error}{dirty?' Tus cambios no se descartaron. Actualizá los permisos si otra persona los modificó.':''}</p>}
  {loading&&!snapshot?<p role="status">Cargando permisos del usuario…</p>:person?<>
   <div className={s.toolbar}><input type="search" aria-label="Buscar permiso" placeholder="Buscar acción, módulo o permiso…" value={search} onChange={e=>setSearch(e.target.value)}/><button onClick={()=>setExpanded(groups)}>Expandir todo</button><button onClick={()=>setExpanded([])}>Contraer todo</button><TooltipAyuda titulo="Permitir y delegar" texto="Permitir habilita una acción. Delegar permite concederla a subordinados, dentro de los límites recibidos. Un permiso marcado puede quedar limitado por el superior, por una cuenta desactivada o por falta del permiso de consulta. Para cambiar de usuario, guardá o descartá los cambios pendientes."/></div>
   <div className={s.scroll} role="region" aria-label={`Permisos de ${person.nombre}`} tabIndex={0}><table className={s.matrix}><colgroup><col/><col style={{width:104}}/><col style={{width:104}}/></colgroup><thead><tr><th scope="col" className={s.action}>Módulo / acción</th><th scope="col">Permitir</th><th scope="col">Delegar</th></tr></thead><tbody>{groups.map(group=>{const defs=permissionCatalog.filter(d=>d.group===group&&matches(d));if(!defs.length)return null;const open=!!search||expanded.includes(group);return <GroupRows key={group} group={group} count={defs.length} open={open} toggle={()=>setExpanded(old=>old.includes(group)?old.filter(v=>v!==group):[...old,group])}>{defs.map(def=><tr key={def.key}><th scope="row" className={s.action}><span>{def.label}</span>{def.help&&<TooltipAyuda titulo={def.label} texto={def.help}/>}<small>{def.planned?'Próximamente':def.key}</small></th>{[false,true].map(delegate=>{const grant=person.permisos.find(v=>v.clave===def.key),value=delegate?grant?.delegable:grant?.permitido,reason=permissionLock(people,person,def,canManage,delegate),effective=value&&effectivePermission(people,person,def.key,delegate);return <td key={String(delegate)}><button className={`${s.cell} ${value&&!effective?s.limited:''}`} disabled={busy||loading||!!reason} aria-pressed={!!value} aria-label={`${person.nombre}: ${delegate?'delegar':'permitir'} ${def.label}`} title={reason||(value&&!effective?'Marcado, pero limitado por la jerarquía, el estado o el permiso de consulta.':undefined)} onClick={()=>{setPeople(old=>togglePermission(old,person.id,def.key,delegate));setMessage('');}}>{value?'✓ Sí':'— No'}</button>{value&&!effective&&<small className={s.limitedText}>Limitado</small>}</td>;})}</tr>)}</GroupRows>;})}{!permissionCatalog.some(matches)&&<tr><td colSpan={3}>No hay permisos que coincidan con la búsqueda.</td></tr>}</tbody></table></div>
   <div className={s.legend}><span><b>✓ Sí</b> marcado</span><span>— No desautorizado</span><span>Limitado: no efectivo</span><span>Botón tenue: bloqueado</span></div>
   <footer className={s.footer}><span role="status" aria-live="polite">{busy?'Guardando permisos…':dirty?'Cambios sin guardar':message||'Sin cambios'}</span><div><button disabled={!dirty||busy} onClick={()=>guard.solicitar(()=>{setPeople(structuredClone(snapshot?.usuarios??[]));setError('');setMessage('Cambios descartados.');},guardId)}>Descartar</button><button className={s.primary} disabled={!dirty||busy||loading||!canManage} onClick={()=>void save()}>Guardar cambios</button></div></footer>
  </>:!error&&<p role="status">Seleccioná un usuario para consultar o administrar sus permisos.</p>}
 </section>;
}
function GroupRows({group,count,open,toggle,children}:{group:string;count:number;open:boolean;toggle:()=>void;children:ReactNode}){return <><tr className={s.group}><th colSpan={3}><button aria-expanded={open} onClick={toggle}>{open?'▾':'▸'} {group} <small>{count} acciones</small></button></th></tr>{open&&children}</>;}
