import {useContext,useEffect,useId,useRef,useState} from 'react';
import {useAccessStore} from '../../stores/accessStore';
import {permissionCatalog} from '../../security/permissionCatalog';
import {changedPermissions,effectivePermission,permissionLock,togglePermission} from '../../security/teamPermissionMatrix';
import {loadTeam,saveTeamPermissions,type TeamPerson,type TeamSnapshot} from '../../services/teamService';
import {GuardiaAdministracionContext} from './guardiaAdministracionContext';
import {AvatarEquipo} from './AvatarEquipo';
import TooltipAyuda from '../ayuda/TooltipAyuda';
import s from './MatrizPermisos.module.css';
const profiles={jefe:'Jefe',tecnico:'Técnico',ayudante:'Ayudante',lector:'Lector'};
const defaults=['Órdenes de trabajo','Fotos y evidencias','Informes'];
const groups=[...defaults,...new Set(permissionCatalog.map(p=>p.group).filter(group=>!defaults.includes(group)))];
export function MatrizPermisos({tenantId,selectedPersonId}:{tenantId:string;selectedPersonId?:string}){
 const guard=useContext(GuardiaAdministracionContext),guardId=useId();
 const context=useAccessStore(v=>v.contexto),company=context?.empresas.find(e=>e.id===tenantId);
 const [snapshot,setSnapshot]=useState<TeamSnapshot|null>(null),[people,setPeople]=useState<TeamPerson[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [search,setSearch]=useState(''),[personSearch,setPersonSearch]=useState(''),[expanded,setExpanded]=useState(defaults),[selected,setSelected]=useState(selectedPersonId??'');
 const lock=useRef(false),mounted=useRef(true);
 const changes=changedPermissions(snapshot?.usuarios??[],people),dirty=changes.length>0;
 useEffect(()=>guard.registrar(guardId,dirty,busy),[guard,guardId,dirty,busy]);
 useEffect(()=>{mounted.current=true;let active=true;void loadTeam(tenantId).then(result=>{if(active){setSnapshot(result);setPeople(structuredClone(result.usuarios));setLoading(false)}}).catch(e=>{if(active){setError(e.message);setLoading(false)}});return()=>{active=false;mounted.current=false}},[tenantId]);
 const canManage=!!context?.creador||!!company?.permisos?.includes('equipo.permisos');
 const order=(list:TeamPerson[])=>{const depth=(person:TeamPerson)=>{let n=0,p=person;const seen=new Set<string>();while(p.superior_id&&!seen.has(p.id)){seen.add(p.id);const next=list.find(v=>v.id===p.superior_id);if(!next)break;p=next;n++;}return n;};return [...list].sort((a,b)=>depth(a)-depth(b)||a.nombre.localeCompare(b.nombre,'es'));};
 const visible=order(people).filter(p=>`${p.nombre} ${p.email} ${profiles[p.perfil]}`.toLocaleLowerCase('es').includes(personSearch.toLocaleLowerCase('es')));
 const person=people.find(p=>p.id===selected)??visible[0];
 async function reload(){if(lock.current)return;setLoading(true);setError('');try{const fresh=await loadTeam(tenantId);if(mounted.current){setSnapshot(fresh);setPeople(structuredClone(fresh.usuarios));setMessage('Matriz actualizada.')}}catch(e){if(mounted.current)setError(e instanceof Error?e.message:'No se pudo actualizar.')}finally{if(mounted.current)setLoading(false)}}
 async function save(){if(lock.current||!changes.length)return;lock.current=true;setBusy(true);setError('');setMessage('');try{const fresh=await saveTeamPermissions(tenantId,changes);if(mounted.current){setSnapshot(fresh);setPeople(structuredClone(fresh.usuarios));setMessage('Permisos guardados. Se aplican también los límites de cada superior.')}}catch(e){if(mounted.current)setError(e instanceof Error?e.message:'No se pudo guardar.')}finally{lock.current=false;if(mounted.current)setBusy(false)}}
 return <section className={s.workspace} aria-label="Matriz de permisos del equipo" aria-busy={loading||busy}>
  <header className={s.header}><div><h2>Permisos del equipo</h2><p>{company?.nombre} · {people.length} personas</p></div><button disabled={busy||loading} onClick={()=>guard.solicitar(()=>void reload(),guardId)}>Actualizar</button></header>
  <div className={s.toolbar}><input type="search" aria-label="Buscar permiso" placeholder="Buscar acción, módulo o permiso…" value={search} onChange={e=>setSearch(e.target.value)}/><input type="search" aria-label="Buscar persona en la matriz" placeholder="Buscar persona…" value={personSearch} onChange={e=>setPersonSearch(e.target.value)}/><button onClick={()=>setExpanded(groups)}>Expandir todo</button><button onClick={()=>setExpanded([])}>Contraer todo</button><TooltipAyuda titulo="Permitir y delegar" texto="Permitir habilita una acción. Delegar permite concederla a subordinados, dentro de los límites recibidos. Un permiso marcado puede quedar limitado por el superior, por una cuenta desactivada o por falta del permiso de consulta. Los cambios se guardan juntos."/></div>
  {person&&<div className={s.identity}><AvatarEquipo person={person}/><div><strong>{person.nombre}</strong><small>{profiles[person.perfil]} · {person.activo?'Activo':'Desactivado'}{person.superior_id?` · depende de ${people.find(p=>p.id===person.superior_id)?.nombre??'su superior'}`:' · máxima autoridad de la empresa'}</small></div><span>Cupos autorizados: <strong>{person.cupos_tecnicos} técnicos · {person.cupos_ayudantes} ayudantes</strong><small>{person.obras.length} obra(s) · {person.editable?'Administrable':'Solo consulta'}</small></span></div>}
  {error&&<p className={s.error} role="alert">{error} Tus cambios no se descartaron. Actualizá la matriz si otra persona modificó los permisos.</p>}
  {loading&&!snapshot?<p role="status">Cargando permisos…</p>:visible.length?<div className={s.scroll} role="region" aria-label="Permisos por acción y persona" tabIndex={0}><table className={s.matrix} style={{minWidth:260+visible.length*184}}><colgroup><col style={{width:260}}/>{visible.map(p=><col key={p.id} span={2} style={{width:92}}/>)}</colgroup><thead><tr><th rowSpan={2} scope="col" className={s.action}>Módulo / acción</th>{visible.map(p=><th key={p.id} colSpan={2} scope="colgroup" className={person?.id===p.id?s.selected:undefined}><button className={s.person} aria-pressed={person?.id===p.id} aria-label={`Seleccionar ${p.nombre}`} onClick={()=>setSelected(p.id)}><AvatarEquipo person={p}/><span>{p.nombre}<small>{profiles[p.perfil]}{!p.activo?' · Desactivado':''}</small></span></button></th>)}</tr><tr>{visible.flatMap(p=>[<th key={p.id+'allow'} scope="col" className={person?.id===p.id?s.selected:undefined}>Permitir</th>,<th key={p.id+'delegate'} scope="col" className={person?.id===p.id?s.selected:undefined}>Delegar</th>])}</tr></thead><tbody>{groups.map(group=>{const defs=permissionCatalog.filter(d=>d.group===group&&`${d.group} ${d.label} ${d.key}`.toLocaleLowerCase('es').includes(search.trim().toLocaleLowerCase('es')));if(!defs.length)return null;const open=!!search||expanded.includes(group);return <GroupRows key={group} group={group} count={defs.length} columns={1+visible.length*2} open={open} toggle={()=>setExpanded(old=>old.includes(group)?old.filter(v=>v!==group):[...old,group])}>{defs.map(def=><tr key={def.key}><th scope="row" className={s.action}><span>{def.label}</span>{def.help&&<TooltipAyuda titulo={def.label} texto={def.help}/>}<small>{def.planned?'Próximamente':def.key}</small></th>{visible.flatMap(p=>[false,true].map(delegate=>{const grant=p.permisos.find(v=>v.clave===def.key),value=delegate?grant?.delegable:grant?.permitido,reason=permissionLock(people,p,def,canManage,delegate),effective=value&&effectivePermission(people,p,def.key,delegate);return <td key={p.id+String(delegate)}><button className={`${s.cell} ${value&&!effective?s.limited:''}`} disabled={busy||loading||!!reason} aria-pressed={!!value} aria-label={`${p.nombre}: ${delegate?'delegar':'permitir'} ${def.label}`} title={reason||(value&&!effective?'Marcado, pero limitado por la jerarquía, el estado o el permiso de consulta.':undefined)} onClick={()=>{setPeople(old=>togglePermission(old,p.id,def.key,delegate));setMessage('')}}>{value?'✓ Sí':'— No'}</button>{value&&!effective&&<small className={s.limitedText}>Limitado</small>}</td>}))}</tr>)}</GroupRows>})}{!permissionCatalog.some(d=>`${d.group} ${d.label} ${d.key}`.toLocaleLowerCase('es').includes(search.trim().toLocaleLowerCase('es')))&&<tr><td colSpan={1+visible.length*2}>No hay permisos que coincidan con la búsqueda.</td></tr>}</tbody></table></div>:<p>No hay personas que coincidan con la búsqueda.</p>}
  <div className={s.legend}><span><b>✓ Sí</b> marcado</span><span>— No desautorizado</span><span>Limitado: no efectivo</span><span>Botón tenue: bloqueado</span></div>
  <footer className={s.footer}><span role="status" aria-live="polite">{busy?'Guardando la matriz…':dirty?`${changes.length} persona(s) con cambios sin guardar`:message||'Sin cambios'}</span><div><button disabled={!dirty||busy} onClick={()=>guard.solicitar(()=>{setPeople(structuredClone(snapshot?.usuarios??[]));setError('');setMessage('Cambios descartados.');},guardId)}>Descartar</button><button className={s.primary} disabled={!dirty||busy||loading||!canManage} onClick={()=>void save()}>Guardar cambios</button></div></footer>
 </section>;
}
function GroupRows({group,count,columns,open,toggle,children}:{group:string;count:number;columns:number;open:boolean;toggle:()=>void;children:React.ReactNode}){return <><tr className={s.group}><th colSpan={columns}><button aria-expanded={open} onClick={toggle}>{open?'▾':'▸'} {group} <small>{count} acciones</small></button></th></tr>{open&&children}</>}
