import {useContext,useEffect,useId,useState} from 'react';
import {supabase} from '../../db/supabase';
import {assertSession,sessionTicket} from '../../security/sessionScope';
import {useAccessStore} from '../../stores/accessStore';
import {type DatosMaestros,type FichaMaestra} from '../../services/masterDirectoryService';
import {PanelAdministracion} from './PanelAdministracion';
import {GuardiaAdministracionContext} from './guardiaAdministracionContext';
import {BuscarFicha,CampoFicha} from './FichasAdministracion';
import s from './FichasAdministracion.module.css';
import styles from './AdministracionCreador.module.css';
interface Ubicacion {id:string;cliente_id:string;proyecto_id:string|null;nombre_obra:string;tipo_inmueble:string;direccion:string|null;piso:string|null;unidad:string|null;sector:string|null;activo:boolean;datos_adicionales:DatosMaestros}
interface Reclamo {id:string;ot:string;estado:string;proyecto_id:string;cliente_ubicacion_id:string|null;created_at:string}
const nueva=():DatosMaestros=>({tipo_inmueble:'residencial_altura',nombre_obra:'',direccion:'',activo:true});
export function UbicacionesAdministracion({tenantId,clienteId,contactos,lectura,onNuevoContacto,permiteAltas=true}:{tenantId:string;clienteId:string;contactos:FichaMaestra[];lectura:boolean;permiteAltas?:boolean;onNuevoContacto:(seleccionar:(id:string)=>void,ubicacion:string)=>void}){
 const guardia=useContext(GuardiaAdministracionContext),guardId=useId();
 const contexto=useAccessStore(s=>s.contexto);
 const obras=contexto?.obras.filter(o=>o.tenant_id===tenantId)??[];
 const [ubicaciones,setUbicaciones]=useState<Ubicacion[]>([]),[historial,setHistorial]=useState<Reclamo[]>([]),[version,setVersion]=useState(0),[editar,setEditar]=useState<string|null>(null),[datos,setDatos]=useState<DatosMaestros>(nueva),[base,setBase]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[texto,setTexto]=useState('');
 useEffect(()=>{let active=true;const ticket=sessionTicket();void Promise.all([supabase.from('plan_cliente_ubicaciones').select('id,cliente_id,proyecto_id,tipo_inmueble,nombre_obra,direccion,piso,unidad,sector,activo,datos_adicionales').eq('tenant_id',tenantId).eq('cliente_id',clienteId).order('nombre_obra'),supabase.from('ordenes').select('id,ot,estado,proyecto_id,cliente_ubicacion_id,created_at').eq('cliente_id',clienteId).order('created_at',{ascending:false}).limit(100)]).then(([u,h])=>{assertSession(ticket);if(u.error||h.error)throw new Error(u.error?.message||h.error?.message);if(active){setUbicaciones((u.data??[]) as Ubicacion[]);setHistorial((h.data??[]) as Reclamo[])}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[tenantId,clienteId,version]);
 useEffect(()=>guardia.registrar(guardId,editar!==null&&JSON.stringify(datos)!==base,busy),[guardia,guardId,editar,datos,base,busy]);
 const abrir=(u?:Ubicacion)=>guardia.solicitar(()=>{const d=u?{...u.datos_adicionales,proyecto_id:u.proyecto_id??'',nombre_obra:u.nombre_obra,tipo_inmueble:u.tipo_inmueble,direccion:u.direccion??'',piso:u.piso??'',unidad:u.unidad??'',sector:u.sector??'',activo:u.activo}:nueva();setDatos(d);setBase(JSON.stringify(d));setEditar(u?.id??'');setError('')});
 const cambiar=(key:string,value:string)=>setDatos(d=>({...d,[key]:value}));
 async function guardar(){if(busy||lectura)return;setBusy(true);setError('');try{const ticket=sessionTicket();const r=await supabase.rpc('plan_directorio_ubicacion_guardar',{p_tenant:tenantId,p_cliente:clienteId,p_id:editar||null,p_datos:datos});assertSession(ticket);if(r.error)throw new Error(r.error.message);setEditar(null);setVersion(v=>v+1)}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.')}finally{setBusy(false)}}
 return <><details className={s.group}><summary>Ubicaciones · {ubicaciones.length}</summary><div className={s.picker}><input type="search" aria-label="Buscar ubicación" placeholder="Buscar dirección, unidad o sector…" value={texto} onChange={e=>setTexto(e.target.value)}/>{ubicaciones.filter(u=>`${u.nombre_obra} ${u.direccion} ${u.unidad} ${u.sector}`.toLocaleLowerCase().includes(texto.toLocaleLowerCase())).map(u=><div key={u.id} className={s.selected}><div><strong>{u.nombre_obra}{u.unidad?` · ${u.unidad}`:''}</strong><small>{u.direccion} · {u.activo?'Activa':'Inactiva'}</small></div><button type="button" className={styles.secondaryButton} onClick={()=>abrir(u)}>{lectura?'Ver':'Editar'}</button></div>)}<button type="button" className={styles.secondaryButton} disabled={lectura||!permiteAltas} onClick={()=>abrir()}>+ Nueva ubicación</button></div></details>
 <details className={s.group}><summary>Historial de reclamos · {historial.length}{historial.length===100?' (últimos 100)':''}</summary>{historial.map(h=><div key={h.id} className={s.link}><strong>{h.ot} · {h.estado}</strong><span>{obras.find(o=>o.id===h.proyecto_id)?.nombre??'Obra anterior'} · {ubicaciones.find(u=>u.id===h.cliente_ubicacion_id)?.nombre_obra??'Ubicación anterior'}</span><small>{new Date(h.created_at).toLocaleDateString('es-PY')}</small></div>)}{!historial.length&&<p className={s.hint}>Todavía no hay reclamos vinculados.</p>}</details>
 {editar!==null&&<PanelAdministracion titulo={lectura?'Ficha de ubicación':editar?'Editar ubicación':'Crear ubicación'} busy={busy} onCerrar={()=>guardia.solicitar(()=>setEditar(null),guardId)} acciones={!lectura&&<button type="button" className={styles.primaryButton} disabled={busy||!String(datos.nombre_obra??'').trim()||!String(datos.direccion??'').trim()} onClick={()=>void guardar()}>Guardar ubicación</button>}><fieldset className={styles.editorFields} disabled={lectura||busy}><div className={s.fields}><label className={`${s.field} ${s.full}`}>Obra / plano vinculado<select value={String(datos.proyecto_id??'')} onChange={e=>cambiar('proyecto_id',e.target.value)}><option value="">Sin obra vinculada</option>{datos.proyecto_id&&!obras.some(o=>o.id===datos.proyecto_id)&&<option value={String(datos.proyecto_id)}>Vínculo existente</option>}{obras.map(o=><option value={o.id} key={o.id}>{o.nombre}</option>)}</select></label><CampoFicha campo={{key:'tipo_inmueble',label:'Tipo de inmueble',opciones:['residencial_altura','oficina_altura','industrial','otro']}} datos={datos} cambiar={cambiar} disabled={lectura||busy}/><label className={s.field}>Estado<select value={datos.activo===false?'inactivo':'activo'} onChange={e=>setDatos(d=>({...d,activo:e.target.value==='activo'}))}><option value="activo">Activa</option><option value="inactivo">Inactiva</option></select></label>{[['nombre_obra','Referencia / nombre de ubicación',true],['direccion','Dirección',true],['torre','Torre / bloque',false],['piso','Piso',false],['unidad','Unidad',false],['sector','Sector',false],['horarios','Horarios de acceso',true],['acceso','Indicaciones de acceso',true]].map(([key,label,full])=><CampoFicha key={String(key)} campo={{key:String(key),label:String(label),full:!!full,area:key==='acceso',max:key==='piso'?40:key==='unidad'?80:key==='sector'?120:key==='direccion'?500:key==='acceso'?4000:160,ejemplo:key==='acceso'?'Ej.: Avisar en recepción antes de ingresar.':undefined}} datos={datos} cambiar={cambiar} disabled={lectura||busy}/>)}</div><BuscarFicha registros={contactos} value={String(datos.contacto_principal_id??'')} onChange={v=>cambiar('contacto_principal_id',v)} label="Contacto de esta ubicación (opcional)" disabled={lectura||busy} nuevoDisabled={!permiteAltas} onNuevo={()=>onNuevoContacto(id=>setDatos(d=>({...d,contacto_principal_id:id})),editar||'')}/><CampoFicha campo={{key:'funcion_contacto',label:'Función del contacto'}} datos={datos} cambiar={cambiar} disabled={lectura||busy}/></fieldset><p className={s.hint}>Cambiar la obra de una ubicación con OTs está bloqueado para conservar su historial.</p>{error&&<p role="alert">{error}</p>}</PanelAdministracion>}{error&&editar===null&&<p role="alert">{error}</p>}</>;
}
