export const RUBROS = [
  'ALBAÑILERÍA', 'ELÉCTRICA', 'PLOMERÍA', 'AA (Aire Acondicionado)',
  'HERRERÍA', 'FISURAS', 'PINTURA', 'MOBILIARIO', 'ABERTURA DE ALUMINIO',
  'ARTEFACTO SANITARIO', 'CERRADURA', 'CIELO RASO', 'ELECTRODOMÉSTICOS',
  'GRANITO', 'LIMPIEZA', 'MAMPARA', 'OTROS', 'PARRILLA',
  'PCI (Protección Contra Incendios)', 'PISCINA', 'PISOS', 'PORTÓN',
  'PUERTA DE MADERA', 'REVESTIMIENTOS', 'SEÑALES DÉBILES', 'TERMO CALEFÓN',
  'ZÓCALO', 'FACHADA', 'PAVIMENTO', 'GRC', 'DEKTON', 'VIDRIOS',
  'VENTILACIÓN MECÁNICA', 'ADMINISTRATIVO', 'RENOVADOR DE AIRE',
  'IMPERMEABILIZACIÓN', 'ESCALERA MECÁNICA',
] as const;

export type Rubro = typeof RUBROS[number];