import {useEffect, useMemo, useState} from 'react';
import {useAccessStore} from '../../stores/accessStore';
import {listarMaestros, type FichaMaestra} from '../../services/masterDirectoryService';
import {fotoDirectorio, DIRECTORIO_FOTO_EVENTO} from '../../services/directoryPhotoService';
import {supabase} from '../../db/supabase';
import {assertSession, sessionTicket} from '../../security/sessionScope';
import {cartelPortal, enlacePortal, type ContextoPortal} from '../../services/portalPilot';
import {coincideBusqueda} from '../../utils/busqueda';
import {SelectorBusqueda} from '../ui/SelectorBusqueda';
import {VoiceInputButton} from '../ui/VoiceInputButton';
import {PortalDialog} from './PortalDialog';
import {PortalReclamosPiloto} from './PortalReclamosPiloto';
import s from './PortalReclamos.module.css';

async function imagenEmbebida(tipo: 'empresa' | 'obra', id: string): Promise<string> {
  const ticket = sessionTicket(), photo = await fotoDirectorio(tipo, id);
  assertSession(ticket);
  if (!photo.path) return '';
  const result = await supabase.storage.from('directory-photos').download(photo.path);
  assertSession(ticket);
  if (result.error || !result.data) throw new Error('No se pudo leer la imagen de Administración.');
  if (result.data.size > 2 * 1024 * 1024 || !['image/jpeg', 'image/png', 'image/webp'].includes(result.data.type)) throw new Error('La imagen de la ficha no tiene un formato admitido.');
  const data = await new Promise<string>((resolve, reject) => {const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error('No se pudo preparar la imagen.')); reader.readAsDataURL(result.data);});
  assertSession(ticket); return data;
}
/** Interfaz piloto, accesible solo al Creador. No escribe reclamos, OT ni configuración. */
export function PortalReclamosAdministracion({tenantId}: {tenantId: string}) {
  const creator = useAccessStore(state => state.disponible && state.contexto?.creador), company = useAccessStore(state => state.contexto?.empresas.find(e => e.id === tenantId));
  const [works, setWorks] = useState<FichaMaestra[]>([]), [workId, setWorkId] = useState(''), [sector, setSector] = useState(''), [tab, setTab] = useState<'qr' | 'reception'>('qr'), [error, setError] = useState(''), [loading, setLoading] = useState(true), [retry, setRetry] = useState(0);
  useEffect(() => {if (!creator) return; let valid = true; void listarMaestros('obra', tenantId).then(data => {if (valid) {setWorks(data.filter(w => w.datos.activo !== false)); setError('');}}).catch(e => {if (valid) setError(e instanceof Error ? e.message : 'No se pudieron cargar las obras.');}).finally(() => {if (valid) setLoading(false);}); return () => {valid = false;};}, [creator, tenantId, retry]);
  const options = works.map(w => ({id: w.id, nombre: String(w.datos.nombre || 'Obra sin nombre'), detalle: String(w.datos.direccion || '')})), work = works.find(w => w.id === workId);
  const context: ContextoPortal = {obraId: workId, obra: String(work?.datos.nombre || ''), empresa: company?.nombre || 'Empresa de prueba', sector: sector.trim()};
  if (!creator) return null;
  const testCompany = coincideBusqueda(company?.nombre || '', 'prueba');
  return <section className={`${s.root} ${s.admin}`}><div className={s.title}><div><h1>Portal de reclamos y QR</h1><p className={s.hint}>QR por obra · recepción y revisión previa · piloto del Creador</p></div><span className={s.badge}>Recepción real sin activar</span></div><div className={s.warning}>Este piloto no recibe solicitudes reales. Primero completaremos y verificaremos el respaldo operativo. WhatsApp se conectará en otra etapa.</div>
  {!testCompany ? <div className={s.empty}>El piloto está disponible para las empresas de prueba. Elegí una de ellas en Empresas → Seleccionar. Las cuentas de Ariel y su equipo no cambian.</div> : <><nav className={s.tabs} aria-label="Portal de reclamos"><button type="button" aria-pressed={tab === 'qr'} onClick={() => setTab('qr')}>QR de la obra</button><button type="button" aria-pressed={tab === 'reception'} onClick={() => setTab('reception')}>Recepción · demostración</button></nav><div className={s.panel}><label className={s.field}><span>Obra</span><SelectorBusqueda label="Obra del portal" value={options.find(o => o.id === workId)} opciones={options} onSeleccionar={id => {setWorkId(id); setSector('');}} onLimpiar={() => setWorkId('')} placeholder={loading ? 'Cargando obras…' : 'Buscar obra por nombre o dirección…'} disabled={loading}/></label>{error && <div className={s.actions}><p className={s.error} role="alert">{error}</p><button type="button" onClick={() => {setLoading(true); setRetry(v => v + 1);}}>Reintentar</button></div>}{!loading && !error && !works.length && <p className={s.hint}>Esta empresa no tiene obras activas. Crealas desde Administración → Obras.</p>}</div>
  {!work ? <div className={s.empty}>Seleccioná una obra para preparar su QR y recorrer el piloto.</div> : tab === 'qr' ? <QRObra key={`${tenantId}-${workId}`} tenantId={tenantId} context={context} sector={sector} setSector={setSector} work={work}/> : <RecepcionPiloto key={workId} context={context}/>}</>}
  </section>;
}

function QRObra({tenantId, context, sector, setSector, work}: {tenantId: string; context: ContextoPortal; sector: string; setSector: (v: string) => void; work: FichaMaestra}) {
  const [logo, setLogo] = useState(''), [photo, setPhoto] = useState(''), [loading, setLoading] = useState(true), [error, setError] = useState(''), [version, setVersion] = useState(0), [dialog, setDialog] = useState<'poster' | 'portal' | null>(null), [notice, setNotice] = useState('');
  useEffect(() => {let valid = true; void Promise.allSettled([imagenEmbebida('empresa', tenantId), imagenEmbebida('obra', context.obraId)]).then(results => {if (!valid) return; setLogo(results[0].status === 'fulfilled' ? results[0].value : ''); setPhoto(results[1].status === 'fulfilled' ? results[1].value : ''); setError(results.some(r => r.status === 'rejected') ? 'No se pudieron cargar todas las imágenes. Reintentá antes de descargar el cartel.' : ''); setLoading(false);}); return () => {valid = false;};}, [tenantId, context.obraId, version]);
  useEffect(() => {const refresh = (event: Event) => {const d = (event as CustomEvent<{tipo: string; id: string}>).detail; if (d && ((d.tipo === 'obra' && d.id === context.obraId) || (d.tipo === 'empresa' && d.id === tenantId))) {setLoading(true); setVersion(v => v + 1);}}; window.addEventListener(DIRECTORIO_FOTO_EVENTO, refresh); return () => window.removeEventListener(DIRECTORIO_FOTO_EVENTO, refresh);}, [context.obraId, tenantId]);
  const link = enlacePortal(window.location.origin, context), svg = useMemo(() => cartelPortal(context, link, logo, photo), [context, link, logo, photo]);
  const image = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
  function download() {if (loading || error) return; const url = URL.createObjectURL(new Blob([svg], {type: 'image/svg+xml;charset=utf-8'})); const a = document.createElement('a'); a.href = url; a.download = `QR-prueba-obra-${context.obraId.replace(/[^a-zA-Z0-9-]/g, '')}.svg`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);}
  async function copy() {try {await navigator.clipboard.writeText(link); setNotice('Enlace de prueba copiado.');} catch {setNotice('No se pudo copiar. Seleccioná el enlace para copiarlo.');}}
  return <div className={s.adminGrid}><div className={s.panel}><div className={s.fixedContext}>{photo && <img src={photo} alt="Miniatura de la obra"/>}<div><h2>{context.obra}</h2><span className={s.hint}>{String(work.datos.direccion || 'Dirección pendiente en la ficha')}</span></div></div><label className={s.field}><span className={s.fieldLabel}>Sector del QR · opcional<VoiceInputButton compact value={sector} onChange={setSector} maxLength={180}/></span><input value={sector} onChange={e => setSector(e.target.value)} maxLength={180} placeholder="Ej.: Recepción · áreas comunes"/></label><div className={s.cloud}><h3>Identidad desde Administración</h3><p className={s.hint}>{loading ? 'Preparando logo y foto…' : `${logo ? 'Logo de empresa incluido' : 'Empresa sin logo cargado'} · ${photo ? 'Foto de obra incluida' : 'Obra sin foto cargada'}`}</p><p className={s.hint}>Las imágenes se muestran fuera del QR y se incorporan al cartel descargado. Podés actualizarlas desde las fichas de Empresa y Obra.</p>{error && <><p className={s.error} role="alert">{error}</p><button type="button" onClick={() => {setLoading(true); setVersion(v => v + 1);}}>Reintentar imágenes</button></>}</div><div className={s.definition}><p><strong>Obra fija.</strong> El cliente no podrá cambiarla desde el formulario.</p><p><strong>Revisión previa.</strong> Cada reclamo recibirá su propio número, fecha y hora antes de vincularse a una OT nueva o existente.</p><p><strong>Activación pendiente.</strong> Respaldo operativo, recepción segura, control de abusos y aviso de privacidad deberán estar verificados.</p></div><label className={s.field}>Enlace de prueba<input readOnly aria-label="Enlace del portal de prueba" value={link} onFocus={e => e.target.select()}/></label><div className={s.actions}><button type="button" className={s.primary} onClick={() => setDialog('portal')}>Probar formulario</button><a href={link} target="_blank" rel="noopener noreferrer">Abrir en otra pestaña</a><button type="button" onClick={() => void copy()}>Copiar enlace</button></div>{notice && <p className={s.hint} role="status">{notice}</p>}<div className={s.divider}><button type="button" disabled title="Disponible cuando se conecte y valide la recepción real">Activar recepción real</button></div></div>
  <div className={`${s.panel} ${s.posterHost}`}><h2>Cartel de la obra</h2><img className={s.poster} src={image} alt={`Cartel QR de prueba para ${context.obra}, con la identidad de Administración`}/><div className={s.actions}><button type="button" onClick={() => setDialog('poster')}>Ampliar cartel</button><button type="button" disabled={loading || !!error} onClick={download}>Descargar SVG</button></div><p className={s.hint}>Escaneable en modo prueba · archivo con imágenes incluidas.</p></div>
  {dialog === 'poster' && <PortalDialog title="Cartel QR · modo prueba" onClose={() => setDialog(null)}><img className={s.poster} src={image} alt="Cartel ampliado"/><div className={s.actions}><button type="button" disabled={loading || !!error} onClick={download}>Descargar SVG</button></div></PortalDialog>}
  {dialog === 'portal' && <PortalDialog title="Probar portal de esta obra" onClose={() => setDialog(null)}><PortalReclamosPiloto context={context} embedded/></PortalDialog>}</div>;
}

interface Solicitud {id: string; nombre: string; unidad: string; descripcion: string; hora: string; estado: string; nota?: string}
function RecepcionPiloto({context}: {context: ContextoPortal}) {
  const [tickets, setTickets] = useState<Solicitud[]>([{id: 'REC-DEMO-0001', nombre: 'Ana López · ejemplo', unidad: '402 · baño', descripcion: 'Se observa humedad en la pared desde ayer.', hora: '08:10', estado: 'Recibido'}, {id: 'REC-DEMO-0002', nombre: 'Carlos Pérez · ejemplo', unidad: 'Áreas comunes', descripcion: 'Una luminaria del pasillo no enciende.', hora: '08:24', estado: 'En revisión'}, {id: 'REC-DEMO-0003', nombre: 'María Gómez · ejemplo', unidad: 'Recepción', descripcion: 'La puerta de acceso no cierra correctamente.', hora: '09:03', estado: 'Recibido'}]), [selected, setSelected] = useState('REC-DEMO-0001'), [query, setQuery] = useState(''), [status, setStatus] = useState('Todos'), [action, setAction] = useState<'new' | 'link' | 'archive' | null>(null), [reason, setReason] = useState(''), [ot, setOt] = useState(''), [message, setMessage] = useState('');
  const current = tickets.find(t => t.id === selected)!, filtered = tickets.filter(t => coincideBusqueda(`${t.id} ${t.nombre} ${t.unidad} ${t.descripcion}`, query) && (status === 'Todos' || t.estado === status));
  const orders = [{id: 'OT-DEMO-001', nombre: 'OT-DEMO-001 · Humedad en baño', detalle: 'Unidad 402 · demostración'}, {id: 'OT-DEMO-002', nombre: 'OT-DEMO-002 · Iluminación', detalle: 'Áreas comunes · demostración'}];
  function change(estado: string, nota?: string) {setTickets(rows => rows.map(t => t.id === selected ? {...t, estado, nota} : t));}
  return <section className={s.admin}><div className={s.title}><div><h2>Reclamos recibidos · demostración</h2><p className={s.hint}>{context.obra} · ejemplos ficticios · más antiguos primero</p></div><span className={s.badge}>Sin registros reales</span></div><div className={s.actions}><input style={{maxWidth:420}} aria-label="Buscar reclamos" placeholder="Buscar número, nombre, unidad o descripción…" value={query} onChange={e => setQuery(e.target.value)}/><select style={{width:'fit-content'}} aria-label="Estado del reclamo" value={status} onChange={e => setStatus(e.target.value)}>{['Todos', 'Recibido', 'En revisión', 'Preparación de OT', 'Vinculado a OT', 'Archivado'].map(v => <option key={v}>{v}</option>)}</select></div><div className={s.receptionGrid}><div className={s.tickets}>{filtered.map(t => <button className={s.ticket} type="button" key={t.id} aria-pressed={t.id === selected} onClick={() => {setSelected(t.id); setMessage('');}}><strong>{t.id} · {t.hora}</strong><span>{t.nombre}</span><small>{t.unidad} · {t.estado}</small><span>{t.descripcion}</span></button>)}{!filtered.length && <div className={s.empty}>No hay coincidencias.</div>}</div><div className={s.panel}><div className={s.title}><h2>{current.id}</h2><span className={s.badge}>{current.estado}</span></div><p>{current.nombre} · {current.unidad}</p><p className={s.hint}>Fecha de ejemplo: 10/10/2026 · {current.hora} · formulario web</p><p>{current.descripcion}</p><p className={s.hint}>El pedido del cliente se conservará separado del diagnóstico del técnico.</p>{current.nota && <p className={s.warning}>{current.nota}</p>}<div className={s.actions}><button type="button" onClick={() => change('En revisión')}>Pasar a revisión</button><button type="button" className={s.primary} onClick={() => setAction('new')}>Preparar OT</button><button type="button" onClick={() => {setOt(''); setAction('link');}}>Vincular a OT</button><button type="button" onClick={() => {setReason(''); setAction('archive');}}>Archivar</button></div><p className={s.hint}>Pedir aclaración y responder por WhatsApp estarán disponibles después de conectar el canal.</p>{message && <p className={s.warning} role="status">{message}</p>}</div></div>
  {action && <PortalDialog title={action === 'new' ? 'Preparar una OT · demostración' : action === 'link' ? 'Vincular a una OT · demostración' : 'Archivar · demostración'} onClose={() => setAction(null)}>{action === 'new' ? <><p>Se trasladarán el pedido original, contacto, fecha y hora y evidencias a la orden de servicio.</p><p className={s.hint}>La ubicación sobre el plano y la evaluación técnica se completarán desde Panel OT. El número único será asignado por el sistema al crear la OT real.</p><button type="button" className={s.primary} onClick={() => {change('Preparación de OT', 'Preparación simulada. No se creó una OT.'); setMessage('Flujo probado. No se creó ninguna OT real.'); setAction(null);}}>Simular preparación</button></> : action === 'link' ? <><SelectorBusqueda label="OT existente" opciones={orders} value={orders.find(o => o.id === ot)} onSeleccionar={setOt} placeholder="Buscar OT por número o descripción…"/><button type="button" className={s.primary} disabled={!ot} onClick={() => {change('Vinculado a OT', `Vínculo simulado: ${ot}`); setMessage('Vinculación de demostración. No se modificó ninguna OT.'); setAction(null);}}>Simular vínculo</button></> : <><label className={s.field}><span className={s.fieldLabel}>Motivo de archivo<VoiceInputButton compact value={reason} onChange={setReason} maxLength={1000}/></span><textarea rows={4} value={reason} onChange={e => setReason(e.target.value)} maxLength={1000} placeholder="Ej.: Solicitud duplicada y revisada por el equipo."/></label><p className={s.hint}>Archivar conserva la solicitud y el motivo. No elimina el reclamo.</p><button type="button" className={s.primary} disabled={!reason.trim()} onClick={() => {change('Archivado', reason.trim()); setMessage('Archivo simulado. Los ejemplos se reinician al salir.'); setAction(null);}}>Simular archivo</button></>}</PortalDialog>}</section>;
}
