import {useEffect, useRef, useState} from 'react';
import {VoiceInputButton} from '../ui/VoiceInputButton';
import type {ContextoPortal} from '../../services/portalPilot';
import {PortalDialog} from './PortalDialog';
import s from './PortalReclamos.module.css';

interface Contacto {nombre: string; telefono: string; correo: string; relacion: string; unidad: string; descripcion: string; atencion: string; previo: string}
interface Foto {id: string; url: string; nombre: string}
const inicial: Contacto = {nombre: '', telefono: '', correo: '', relacion: 'Propietario/a', unidad: '', descripcion: '', atencion: 'No', previo: 'No'};
export function PortalReclamosPiloto({context, embedded = false}: {context: ContextoPortal; embedded?: boolean}) {
  const [data, setData] = useState<Contacto>(inicial), [photos, setPhotos] = useState<Foto[]>([]), [consent, setConsent] = useState(false), [view, setView] = useState<'form' | 'review' | 'receipt'>('form'), [error, setError] = useState(''), [tracking, setTracking] = useState(false), [sentAt, setSentAt] = useState('');
  const form = useRef<HTMLFormElement>(null), camera = useRef<HTMLInputElement>(null), gallery = useRef<HTMLInputElement>(null), photoRefs = useRef<Foto[]>([]);
  useEffect(() => () => {photoRefs.current.forEach(p => URL.revokeObjectURL(p.url));}, []);
  const update = (key: keyof Contacto, value: string) => {setData(d => ({...d, [key]: value})); setError('');};
  function add(files: FileList | null) {
    if (!files?.length) return;
    const selected = Array.from(files);
    if (selected.some(file => !['image/jpeg', 'image/png', 'image/webp'].includes(file.type) || file.size > 8 * 1024 * 1024)) {setError('Elegí fotos JPG, PNG o WebP de hasta 8 MB cada una.'); return;}
    if (selected.length + photos.length > 3) {setError('En esta demostración podés agregar hasta tres fotos.'); return;}
    const next = [...photos, ...selected.map(file => ({id: crypto.randomUUID(), url: URL.createObjectURL(file), nombre: file.name}))]; photoRefs.current = next; setPhotos(next); setError('');
  }
  function remove(id: string) {const item = photos.find(p => p.id === id); if (item) URL.revokeObjectURL(item.url); const next = photos.filter(p => p.id !== id); photoRefs.current = next; setPhotos(next);}
  function review() {if (!form.current?.reportValidity()) return; if (![data.nombre, data.unidad, data.descripcion].every(v => v.trim()) || !/\d{6,}/.test(data.telefono.replace(/\D/g, ''))) {setError('Completá nombre, un teléfono válido, unidad o sector y descripción.'); return;} setError(''); setView('review');}
  const field = (key: keyof Contacto, label: string, placeholder: string, required = false, type = 'text', voice = true, area = false) => <label className={`${s.field} ${area ? s.wide : ''}`}><span className={s.fieldLabel}>{label}{required && ' *'}{voice && <VoiceInputButton compact value={data[key]} onChange={v => update(key, v)} maxLength={area ? 4000 : 180}/>}</span>{area ? <textarea rows={4} required={required} maxLength={4000} aria-label={label} placeholder={placeholder} value={data[key]} onChange={e => update(key, e.target.value)}/> : <input required={required} aria-label={label} maxLength={180} type={type} placeholder={placeholder} value={data[key]} onChange={e => update(key, e.target.value)}/>}</label>;
  return <div className={`${s.root} ${embedded ? '' : s.public}`}><section className={s.portal} aria-label="Portal de reclamos"><header className={s.portalHeader}><div className={s.brand}><b>P</b><div><strong>Plan-OTs</strong><small>Portal de reclamos</small></div></div><button type="button" onClick={() => setTracking(true)}>Consultar reclamo</button></header>
  {view === 'receipt' ? <div className={s.receipt}><span className={s.receiptIcon}>✓</span><span className={s.badge}>Confirmación de prueba</span><h1>Así recibirías tu comprobante</h1><strong>REC-DEMO-0001</strong><p className={s.hint}>{sentAt}</p><div className={s.timeline}><strong>Recibido</strong><span>→ En revisión</span><span>→ Seguimiento</span></div><div className={s.warning}>Recepción simulada. No se guardó ni se envió un reclamo real.</div><p className={s.hint}>Cada reclamo tendrá su propio número. Una OT solo se generará después de la revisión del equipo.</p><button type="button" onClick={() => {setView('form'); setConsent(false);}}>Volver al formulario</button></div> : <div className={s.portalBody}><div className={s.intro}><span className={s.badge}>Modo prueba · recepción sin activar</span><h1>{view === 'review' ? 'Revisá antes de enviar' : 'Contanos qué pasó'}</h1><span className={s.workBadge}>{context.obra}</span><p className={s.meta}>{context.empresa}{context.sector && ` · Sector: ${context.sector}`}</p><p className={s.hint}>La obra viene definida por este QR. {view === 'form' && 'Los campos con * son obligatorios.'}</p></div>
  {view === 'review' ? <><section className={`${s.cloud} ${s.review}`}><h2>Tu solicitud</h2><dl className={s.reviewList}>{[['Nombre', data.nombre], ['Teléfono', data.telefono], ['Correo', data.correo || 'Sin indicar'], ['Relación', data.relacion], ['Unidad / sector', data.unidad], ['Descripción', data.descripcion], ['Atención inmediata declarada', data.atencion], ['Reportado anteriormente', data.previo], ['Evidencia', `${photos.length} foto(s)`]].map(([label, value]) => <div key={label} className={s.wide}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className={s.photoRow}>{photos.map(p => <div className={s.thumb} key={p.id}><img src={p.url} alt={p.nombre}/></div>)}</div></section><div className={s.warning}>Es una demostración: la confirmación no envía datos ni inicia una orden de trabajo.</div><div className={s.actions}><button type="button" onClick={() => setView('form')}>Corregir datos</button><button className={s.primary} type="button" onClick={() => {setSentAt(new Date().toLocaleString('es-PY')); setView('receipt');}}>Simular envío</button></div></> : <form ref={form} onSubmit={e => {e.preventDefault(); review();}} className={s.admin}>
  <section className={`${s.cloud} ${s.contact}`}><div className={s.cloudTitle}><span className={s.step}>1</span><h2>Tu contacto</h2></div><div className={s.fields}>{field('nombre', 'Nombre y apellido', 'Ej.: Ana López', true, 'text', true)}{field('telefono', 'Teléfono', 'Ej.: +595 981 123 456', true, 'tel')}{field('correo', 'Correo electrónico', 'Ej.: ana@ejemplo.com', false, 'email')}<label className={s.field}>Relación con la obra<select value={data.relacion} onChange={e => update('relacion', e.target.value)}>{['Propietario/a', 'Inquilino/a', 'Administración', 'Otro'].map(v => <option key={v}>{v}</option>)}</select></label></div></section>
  <section className={s.cloud}><div className={s.cloudTitle}><span className={s.step}>2</span><h2>El reclamo</h2></div><div className={s.fields}>{field('unidad', 'Unidad o sector', 'Ej.: Departamento 402 · baño', true, 'text', true)}<label className={s.field}>¿Requiere atención inmediata?<select value={data.atencion} onChange={e => update('atencion', e.target.value)}><option>No</option><option>Sí</option><option>No estoy seguro/a</option></select></label>{field('descripcion', 'Descripción del reclamo', 'Ej.: Desde ayer se observa humedad en la pared del baño. Contanos dónde ocurre y desde cuándo.', true, 'text', true, true)}<label className={`${s.field} ${s.wide}`}>¿Ya lo habías reportado?<select value={data.previo} onChange={e => update('previo', e.target.value)}><option>No</option><option>Sí</option><option>No estoy seguro/a</option></select></label></div><p className={s.hint}>Tu percepción ayuda a revisar el pedido. El equipo definirá la prioridad y la clasificación técnica.</p></section>
  <section className={`${s.cloud} ${s.photos}`}><div className={s.cloudTitle}><span className={s.step}>3</span><h2>Fotos del problema</h2></div><p className={s.hint}>Opcionales en este piloto · hasta tres fotos · JPG, PNG o WebP · 8 MB por foto.</p><div className={s.photoRow}><button type="button" className={s.photoButton} disabled={photos.length === 3} onClick={() => camera.current?.click()}><PhotoIcon/><span>Cámara</span></button><button type="button" className={s.photoButton} disabled={photos.length === 3} onClick={() => gallery.current?.click()}><PhotoIcon gallery/><span>Galería</span></button>{photos.map(p => <div key={p.id} className={s.thumb}><img src={p.url} alt={p.nombre}/><button type="button" className={s.removePhoto} aria-label={`Quitar ${p.nombre}`} onClick={() => remove(p.id)}>×</button></div>)}</div><input ref={camera} className={s.file} aria-label="Tomar foto" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e => {add(e.target.files); e.target.value = '';}}/><input ref={gallery} className={s.file} aria-label="Elegir fotos" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e => {add(e.target.files); e.target.value = '';}}/><p className={s.hint}>Las fotos permanecen solo en esta pantalla de prueba. No se suben al servidor.</p></section>
  <label className={s.consent}><input type="checkbox" required checked={consent} onChange={e => setConsent(e.target.checked)}/><span>Autorizo el uso de mis datos para atender esta solicitud y contactarme. <small className={s.hint}>Texto propuesto para el portal; se validará antes de habilitar la recepción real.</small></span></label>{error && <p className={s.error} role="alert">{error}</p>}<div className={s.actions}><button type="submit" className={s.primary}>Revisar solicitud</button><span className={s.hint}>Sin envío real</span></div></form>}</div>}</section>
  {tracking && <PortalDialog title="Consultar un reclamo" onClose={() => setTracking(false)}><p>El seguimiento público se habilitará junto con la recepción real.</p><div className={s.warning}>En producción, el número de reclamo requerirá una verificación de contacto para proteger los datos del cliente.</div><p className={s.hint}>La solicitud de esta demostración no queda registrada.</p></PortalDialog>}</div>;
}
function PhotoIcon({gallery = false}: {gallery?: boolean}) {return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true">{gallery ? <><rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="1.5"/><path d="m3 17 5-5 4 4 3-3 6 6"/></> : <><path d="M4 6h4l2-3h4l2 3h4v14H4z"/><circle cx="12" cy="13" r="4"/></>}</svg>;}
