import { useEffect, useState } from 'react';
import { supabase } from '../../db/supabase';
import { assertSession,sessionTicket } from '../../security/sessionScope';
import { fichaObra,type FichaObra,type ContactoObra } from '../../services/workDirectoryService';
import { DialogDirectorioOT } from './DialogDirectorioOT';
import { VoiceInputButton } from '../ui/VoiceInputButton';
import styles from './DatosVinculados.module.css';

const empty={nombre:'',cargo:'',telefono:'',correo:''};
export function FichaObraOT({proyectoId,puedeGestionar=false}:{proyectoId:string;puedeGestionar?:boolean}) {
 const [ficha,setFicha]=useState<FichaObra|null>(null),[error,setError]=useState(''),[version,setVersion]=useState(0);
 const [dialog,setDialog]=useState<'ficha'|'contacto'|null>(null),[contactoId,setContactoId]=useState<string|null>(null);
 const [datos,setDatos]=useState(empty),[busy,setBusy]=useState(false),[texto,setTexto]=useState('');
 useEffect(()=>{let active=true;void fichaObra(proyectoId).then(f=>{if(active){setFicha(f);setError('')}}).catch(e=>{if(active){setFicha(null);setError(e.message)}});return()=>{active=false}},[proyectoId,version]);
 function editar(c?:ContactoObra){setContactoId(c?.id??null);setDatos(c?{nombre:c.nombre,cargo:c.cargo??'',telefono:c.telefono??'',correo:c.correo??''}:empty);setError('');setDialog('contacto')}
 async function guardar(){if(busy||!datos.nombre.trim())return;if(datos.correo&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(datos.correo)){setError('Revisá el correo del contacto.');return}setBusy(true);setError('');try{const ticket=sessionTicket();const {error}=await supabase.rpc('plan_guardar_contacto_obra',{p_proyecto:proyectoId,p_id:contactoId,p_nombre:datos.nombre,p_cargo:datos.cargo,p_telefono:datos.telefono,p_correo:datos.correo});assertSession(ticket);if(error)throw new Error(error.message);setDialog('ficha');setVersion(v=>v+1)}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.')}finally{setBusy(false)}}
 const items=ficha?.contactos.filter(c=>`${c.nombre} ${c.cargo??''} ${c.telefono??''}`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(texto.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()))??[];
 const content=<><dl className={styles.ficha}><div><dt>Obra</dt><dd>{ficha?.nombre??'Cargando…'}</dd></div><div><dt>Dirección de la obra</dt><dd>{ficha?.direccion||'Sin registrar'}</dd></div></dl><div className={styles.tools}><label className={styles.search}>Buscar contacto de la obra<input type="search" value={texto} onChange={e=>setTexto(e.target.value)} placeholder="Nombre, cargo o teléfono…"/></label><button type="button" className={styles.button} disabled={!puedeGestionar||!ficha||busy} onClick={()=>editar()}>+ Nuevo contacto</button></div>{items.map(c=><div key={c.id} className={styles.contact}><dl className={styles.ficha}><div><dt>Contacto de la obra</dt><dd>{c.nombre}</dd></div><div><dt>Cargo / función</dt><dd>{c.cargo||'Sin registrar'}</dd></div><div><dt>Teléfono</dt><dd>{c.telefono||'Sin registrar'}</dd></div><div><dt>Correo</dt><dd>{c.correo||'Sin registrar'}</dd></div></dl><button type="button" className={styles.button} disabled={!puedeGestionar||busy} onClick={()=>editar(c)}>Editar contacto</button></div>)}{ficha&&!items.length&&<p className={styles.note}>{texto?'No hay coincidencias.':'Sin contactos de obra registrados.'}</p>}</>;
 return <><dl className={styles.ficha}><div><dt>Obra</dt><dd>{ficha?.nombre??'Cargando ficha…'}</dd></div><div><dt>Contacto de la obra</dt><dd>{ficha?.contactos.map(c=>`${c.nombre}${c.cargo?` · ${c.cargo}`:''}`).join('; ')||'Sin registrar'}</dd></div><div><dt>Teléfono</dt><dd>{ficha?.contactos.map(c=>c.telefono).filter(Boolean).join(' · ')||'Sin registrar'}</dd></div><div><dt>Correo</dt><dd>{ficha?.contactos.map(c=>c.correo).filter(Boolean).join(' · ')||'Sin registrar'}</dd></div></dl><a href="#ficha-obra" role="button" className={styles.button} aria-disabled={!ficha} tabIndex={ficha?0:-1} onClick={e=>{e.preventDefault();if(ficha)setDialog('ficha')}} onKeyDown={e=>{if(e.key===' '){e.preventDefault();if(ficha)setDialog('ficha')}}}>Ver ficha de la obra</a>{error&&!dialog&&<p role="alert">{error}</p>}
 {dialog&&<DialogDirectorioOT titulo={dialog==='ficha'?'Ficha de la obra':contactoId?'Editar contacto de la obra':'Nuevo contacto de la obra'} busy={busy} onCerrar={()=>setDialog(null)}>{dialog==='ficha'?content:<><p className={styles.note}>Contacto del inmueble. Este registro no crea una cuenta ni asigna permisos.</p><fieldset disabled={busy} className={styles.grid}>{([['nombre','Nombre',160],['cargo','Cargo / función',160],['telefono','Teléfono',80],['correo','Correo',254]] as const).map(([key,label,max])=><label key={key} className={styles.field}><span className={styles.label}>{label}<VoiceInputButton compact value={datos[key]} maxLength={max} onChange={v=>setDatos(d=>({...d,[key]:v}))}/></span><input type={key==='correo'?'email':key==='telefono'?'tel':'text'} value={datos[key]} maxLength={max} onChange={e=>setDatos(d=>({...d,[key]:e.target.value}))}/></label>)}</fieldset><div className={styles.tools}><button type="button" className={styles.button} disabled={busy||!datos.nombre.trim()} onClick={()=>void guardar()}>{busy?'Guardando…':'Guardar contacto'}</button><button type="button" className={styles.button} disabled={busy} onClick={()=>setDialog('ficha')}>Cancelar</button></div></>}{error&&<p role="alert">{error}</p>}</DialogDirectorioOT>}</>;
}
