import {useEffect,useId,useLayoutEffect,useRef,useState,type CSSProperties} from 'react';
import {createPortal} from 'react-dom';
import {coincideBusqueda,normalizarBusqueda} from '../../utils/busqueda';
import s from './SelectorBusqueda.module.css';
export interface OpcionBusqueda {id:string;nombre:string;detalle?:string;busqueda?:string}
interface Props {label:string;value?:OpcionBusqueda;opciones?:OpcionBusqueda[];buscar?:(texto:string)=>Promise<OpcionBusqueda[]>;onSeleccionar:(id:string)=>void;onLimpiar?:()=>void;placeholder?:string;disabled?:boolean}
export function SelectorBusqueda({label,value,opciones=[],buscar,onSeleccionar,onLimpiar,placeholder='Empezá a escribir…',disabled=false}:Props){
 const id=useId(),anchor=useRef<HTMLDivElement>(null),menu=useRef<HTMLDivElement>(null),input=useRef<HTMLInputElement>(null);
 const [open,setOpen]=useState(false),[texto,setTexto]=useState(''),[results,setResults]=useState<OpcionBusqueda[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[active,setActive]=useState(-1),[position,setPosition]=useState<CSSProperties>({top:0,left:0,width:0,maxHeight:280});
 const filtered=buscar?results:opciones.filter(o=>coincideBusqueda(o.busqueda??`${o.nombre} ${o.detalle??''}`,texto)).slice(0,20);
 useEffect(()=>{if(!open||!buscar)return;let valid=true;const timer=setTimeout(()=>{void buscar(normalizarBusqueda(texto)).then(data=>{if(valid){setResults(data.slice(0,20));setActive(-1);}}).catch(e=>{if(valid)setError(e instanceof Error?e.message:'No se pudo buscar.');}).finally(()=>{if(valid)setLoading(false);});},180);return()=>{valid=false;clearTimeout(timer);};},[open,texto,buscar]);
 useLayoutEffect(()=>{if(!open)return;const update=()=>{const rect=anchor.current?.getBoundingClientRect();if(!rect)return;const height=document.documentElement.clientHeight,width=document.documentElement.clientWidth,below=height-rect.bottom-8,above=rect.top-8,up=below<180&&above>below,maxHeight=Math.min(280,Math.max(80,up?above:below));setPosition({top:up?undefined:rect.bottom+4,bottom:up?height-rect.top+4:undefined,left:Math.max(8,Math.min(rect.left,width-Math.min(rect.width,width-16)-8)),width:Math.min(rect.width,width-16),maxHeight});};update();window.addEventListener('resize',update);window.addEventListener('scroll',update,true);return()=>{window.removeEventListener('resize',update);window.removeEventListener('scroll',update,true);};},[open]);
 useEffect(()=>{if(!open)return;const outside=(e:PointerEvent)=>{if(!anchor.current?.contains(e.target as Node)&&!menu.current?.contains(e.target as Node))setOpen(false);};document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside);},[open]);
 const choose=(option:OpcionBusqueda)=>{setOpen(false);setTexto('');setActive(-1);onSeleccionar(option.id);input.current?.focus();};
 const begin=(text:string)=>{setTexto(text);setResults([]);setError('');setActive(-1);setLoading(!!buscar);setOpen(true);};
 useEffect(()=>{if(active>=0)menu.current?.querySelector<HTMLElement>(`[data-active="true"]`)?.scrollIntoView({block:'nearest'});},[active]);
 return <div ref={anchor} className={s.field}><input ref={input} role="combobox" aria-label={label} aria-autocomplete="list" aria-expanded={open&&!disabled} aria-controls={open?id:undefined} aria-activedescendant={open&&active>=0?`${id}-${active}`:undefined} autoComplete="off" disabled={disabled} placeholder={placeholder} value={open?texto:value?.nombre??''} onFocus={()=>begin('')} onClick={()=>{if(!open)begin('');}} onChange={e=>begin(e.target.value)} onBlur={e=>{if(!menu.current?.contains(e.relatedTarget as Node))setOpen(false);}} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();setOpen(false);}else if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();if(!open){begin('');return;}setActive(previous=>filtered.length?(previous<0?(e.key==='ArrowDown'?0:filtered.length-1):(previous+(e.key==='ArrowDown'?1:-1)+filtered.length)%filtered.length):-1);}else if(e.key==='Enter'&&open){e.preventDefault();if(!loading&&filtered[active])choose(filtered[active]);}}}/>{value&&onLimpiar&&<button type="button" className={s.clear} disabled={disabled} aria-label={`Limpiar ${label}`} onClick={()=>{setOpen(false);setTexto('');onLimpiar();}}>×</button>}{open&&!disabled&&createPortal(<div ref={menu} className={s.menu} style={position}><div id={id} role="listbox" aria-label={`Opciones de ${label}`} aria-busy={loading}>{loading?<span className={s.hint} role="status">Buscando…</span>:error?<p className={s.error} role="alert">{error}</p>:filtered.length?filtered.map((option,index)=><button key={option.id} type="button" id={`${id}-${index}`} role="option" aria-selected={value?.id===option.id} data-active={active===index} className={s.option} onPointerDown={e=>e.preventDefault()} onClick={()=>choose(option)}><strong>{option.nombre}</strong>{option.detalle&&<small>{option.detalle}</small>}</button>):<span className={s.hint}>No hay coincidencias.</span>}</div>{filtered.length===20&&<small className={s.hint}>Hasta 20 opciones. Escribí más letras para acotar la búsqueda.</small>}</div>,document.body)}</div>;
}
